name: xcode-select
runs:
  using: "composite"
  steps:
    - name: Select Xcode version
      # See: https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md#xcode
      run: sudo xcode-select -s '/Applications/Xcode_15.3.app'
      shell: bash
    - name: Show Xcode version
      id: xcode-version
      run: echo `xcodebuild -version`
      shell: bash
