name: CI
on:
  pull_request:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    # Use Ubuntu 22.04 due to https://github.com/swift-actions/setup-swift/issues/677
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.9"
      - uses: actions/checkout@v4
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
